version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    versioning-strategy: widen
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
