name: Code Style

on: [pull_request]

jobs:
  fix-code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: Run prettier
        uses: actionsx/prettier@v2
        with:
          args: --write .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Markus Poerschke (Bot)
          commit_user_email: markus+githubbot@poerschke.nrw
          commit_message: Fix code style!
