name: "Danger JS"
on: [pull_request]

jobs:
  danger:
    name: Danger JS
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Danger
        uses: danger/danger-js@11.0.2
        env:
          DANGER_DISABLE_TRANSPILATION: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
